### ISSUE TITLE
Trying to install inside Arduino IDE but get error...

### ISSUE THREAD

**Issue by TheStigh** [khoih-prog/ESPAsync_WiFiManager#11]
Hi, got Arduino IDE 1.8.13 and are using ESP_WiFiManager today with success.
Wanted to update to ESPAsync_WiFiManager but at library install I get following error in A-IDE:

` no protocol: 
java.lang.RuntimeException: java.net.MalformedURLException: no protocol: 
	at cc.arduino.contributions.libraries.ui.LibraryManagerUI.lambda$onInstallPressed$4(LibraryManagerUI.java:248)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.MalformedURLException: no protocol: 
	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:64)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:60)
	at cc.arduino.contributions.libraries.LibraryInstaller.performInstall(LibraryInstaller.java:155)
	at cc.arduino.contributions.libraries.LibraryInstaller.install(LibraryInstaller.java:125)
	at cc.arduino.contributions.libraries.ui.LibraryManagerUI.lambda$onInstallPressed$4(LibraryManagerUI.java:237)
	... 1 more
`
Any idea what is wrong or how to resolve this ?

**Comment by khoih-prog** [comment]
@TheStigh 

You have to ask the question in Arduino forum as this has nothing to do with the library.
You can also install manually. Have a look at [*Manual-Install**](https://github.com/khoih-prog/ESPAsync_WiFiManager#manual-install)
